raw_restaurant_list = [
    {
        "Name": "test_restaurant_1",
        "Url": "http://test.url/1",
        "RatingAverage": 2.8,
        "Cuisines": [{"Name": "Pizza"}, {"Name": "Italian"}],
        "DeliveryEtaMinutes": {"RangeLower": 15, "RangeUpper": 30},
        "IsDelivery": True,
        "IsOpenNowForDelivery": True,
    },
    {
        "Name": "test_restaurant_2",
        "Url": "http://test.url/2",
        "RatingAverage": 4.3,
        "Cuisines": [{"Name": "Salad"}, {"Name": "Vegan"}],
        "DeliveryEtaMinutes": {"RangeLower": 75, "RangeUpper": 150},
        "IsDelivery": True,
        "IsOpenNowForDelivery": True,
    },
    {
        "Name": "test_restaurant_3",
        "Url": "http://test.url/3",
        "RatingAverage": 6.0,
        "Cuisines": [{"Name": "Salad"}, {"Name": "Vegan"}],
        "DeliveryEtaMinutes": {"RangeLower": 10, "RangeUpper": 25},
        "IsDelivery": True,
        "IsOpenNowForDelivery": True,
    },
    {
        "Name": "test_restaurant_4_!IsDelivery",
        "Url": "http://test.url/4",
        "RatingAverage": 0.1,
        "Cuisines": [{"Name": "Misery"}, {"Name": "Suffering"}],
        "DeliveryEtaMinutes": {"RangeLower": 1000, "RangeUpper": 10000},
        "IsDelivery": False,
        "IsOpenNowForDelivery": True,
    },
    {
        "Name": "test_restaurant_5_!IsOpenNowForDelivery",
        "Url": "http://test.url/5",
        "RatingAverage": 0.1,
        "Cuisines": [{"Name": "Misery"}, {"Name": "Suffering"}],
        "DeliveryEtaMinutes": {"RangeLower": 1000, "RangeUpper": 10000},
        "IsDelivery": True,
        "IsOpenNowForDelivery": False,
    },
]
